Repository Normation/rudder-techniques, pull requests merged in 2018-06, with the labels that each got.

#1310 Fixes #12745: SSH Configuration Technique on AIX does not reload correctly sshd service when there's been a change
  techniques/systemSettings/remoteAccess/sshConfiguration/4.0/main.st
  techniques/systemSettings/remoteAccess/sshConfiguration/5.0/main.st
Labels: qa: Can't merge

#1308 Fixes #12713: Misleading error message in Services technique when range of number of process could not be repaired
  techniques/systemSettings/process/servicesManagement/3.0/servicesManagement.st
Labels: Ready for merge

#1312 Fixes #12774: Load modules from local ncf in Rudder policies
  techniques/system/common/1.0/promises.st
Labels: Ready for merge, qa: Can't merge

#1311 Fixes #12762: Add zypper_pattern provider in package technique
  techniques/applications/packageManagement/1.0/metadata.xml
  techniques/applications/packageManagement/1.1/metadata.xml
Labels: qa: Can't merge

#1317 Fixes #12155: Detection of minicurl and https is done in conflicting ways
  techniques/system/inventory/1.0/fusionAgent.st
Labels: qa: Can't merge

#1316 Fixes #12793: Rudder agent needs 2 updates to work properly
  techniques/system/common/1.0/update.st
Labels: qa: Can't merge
