Repository Normation/rudder-techniques, pull requests merged in 2019-10, with the labels that each got.

#1518 Fixes #15818: Bootstrap policies should listen on 5309
  .gitignore
  bootstrap-promises/failsafe.cf
Labels: qa: Can't merge

#1524 Fixes #15840: fileManagement can not remove files with last modification date in the future
  techniques/fileConfiguration/fileManagement/4.1/manageFilesAndFolders.st
Labels: qa: Can't merge

#1424 Fixes #14296: System technique try to edit pg_hba file only on SUSE, but packaging takes care of this part
  techniques/system/server-roles/1.0/metadata.xml
  techniques/system/server-roles/1.0/postgres-check.st
Labels: qa: Can't merge

#1527 Fixes #15872: Policy generation failed because of parent ticket
  techniques/system/server-roles/1.0/component-check.st
Labels: Ready for merge, qa: Can't merge

#1528 Fixes #15877: Wrong tabulation fixed in 15841
  techniques/fileConfiguration/fileManagement/4.1/manageFilesAndFolders.st
Labels: Ready for merge

#1531 Fixes #15899: postgres-check.cf doesn't exist anymore but is still loaded
  techniques/system/common/1.0/promises.st
  techniques/system/server-roles/1.0/metadata.xml
Labels: Ready for merge

#1530 Fixes #15894: if we add a ssh key for a user without home, it create a /.ssh folder
  techniques/system/common/1.0/hooks.st
  techniques/systemSettings/remoteAccess/sshKeyDistribution/4.0/sshKeyDistribution.st
Labels: Ready for merge, qa: Can't merge

#1529 Fixes #15891: Change technique_name in reporting for services techniques
  techniques/systemSettings/process/services/1.1/services.st
  techniques/systemSettings/process/servicesManagement/3.0/servicesManagement.st
Labels: qa: Can't merge

#1544 Fixes #16020: don't edit the cron file in the initial promises
  Makefile
Labels: qa: Can't merge

#1545 Fixes #16022: Reload relayd when updating nodeslist.json on relays
  techniques/system/distributePolicy/1.0/propagatePromises.cf
Labels: qa: Can't merge

#1546 Fixes #16028: Initial policies on root server broken with missing postgres-check.cf file
  techniques/system/common/1.0/promises.st
Labels: qa: Can't merge

#1537 Fixes #15993: In a separate database setup, an unexpected N/A report about "Postgresql component check" pops up
  techniques/system/server-roles/1.0/component-check.st
Labels: qa: Can't merge

#1549 Fixes #16064: Typo in the system technique PropagatePromises
  techniques/system/distributePolicy/1.0/propagatePromises.st
Labels: Ready for merge, qa: Can't merge
