Repository Normation/rudder-techniques, pull requests merged in 2020-10, with the labels that each got.

#1626 Fixes #18286
  techniques/system/common/1.0/cf-serverd.st
  techniques/system/common/1.0/failsafe.st
  techniques/system/common/1.0/metadata.xml
  techniques/system/common/1.0/promises.st
  techniques/system/common/1.0/update.st
Labels: Trigger test, qa: Can't merge

#1627 Fixes #18293:
  bootstrap-promises/failsafe.cf
Labels: Trigger test, WIP, qa: Can't merge

#1631 Fixes #18341: Remove os/name tags from techniques' metadata.xml
  technique-metadata-sample.xml
  techniques/applications/packageManagement/1.2/metadata.xml
  techniques/applications/repoGpgKeyManagement/1.1/metadata.xml
  techniques/applications/zmdPackageManagerSettings/3.0/metadata.xml
  techniques/applications/zypperPackageManagerRepositories/1.0/metadata.xml
  techniques/applications/zypperPackageManagerSetup/1.0/metadata.xml
  techniques/fileConfiguration/fileManagement/4.1/metadata.xml
  techniques/fileConfiguration/fileSecurity/filesPermissions/2.2/metadata.xml
  techniques/fileDistribution/checkGenericFileContent/8.0/metadata.xml
  techniques/fileDistribution/copyGitFile/2.3/metadata.xml
  techniques/fileDistribution/manageKeyValueFile/1.3/metadata.xml
  techniques/jobScheduling/jobScheduler/2.0/metadata.xml
  techniques/jobScheduling/jobScheduler/3.0/metadata.xml
  techniques/systemSettings/misc/clockConfiguration/3.2/metadata.xml
  techniques/systemSettings/misc/genericCommandVariableDefinition/3.0/metadata.xml
  techniques/systemSettings/misc/genericVariableDefinition/2.0/metadata.xml
  techniques/systemSettings/misc/partitionSizeMonitoring/3.1/metadata.xml
  techniques/systemSettings/misc/variableFromJsonFile/2.0/metadata.xml
  techniques/systemSettings/misc/variableFromJsonFile/3.0/metadata.xml
  techniques/systemSettings/networking/dnsConfiguration/3.0/metadata.xml
  techniques/systemSettings/networking/firewall/1.0/metadata.xml
  techniques/systemSettings/networking/hostsConfiguration/2.0/metadata.xml
  techniques/systemSettings/networking/nfsClient/3.0/metadata.xml
  techniques/systemSettings/networking/routingManagement/2.0/metadata.xml
  techniques/systemSettings/process/servicesManagement/3.0/metadata.xml
  techniques/systemSettings/remoteAccess/sshConfiguration/5.0/metadata.xml
  techniques/systemSettings/remoteAccess/sshKeyDistribution/3.0/metadata.xml
  techniques/systemSettings/remoteAccess/sshKeyDistribution/4.0/metadata.xml
  techniques/systemSettings/security/fileAlterationMonitoring/2.2/metadata.xml
  techniques/systemSettings/systemManagement/cronManagement/3.1/metadata.xml
  techniques/systemSettings/systemManagement/cronManagement/3.2/metadata.xml
  techniques/systemSettings/systemManagement/fstabConfiguration/4.0/metadata.xml
  techniques/systemSettings/systemManagement/motdConfiguration/3.2/metadata.xml
  techniques/systemSettings/systemManagement/motdConfiguration/3.3/metadata.xml
  techniques/systemSettings/userManagement/sudoParameters/3.2/metadata.xml
  techniques/systemSettings/userManagement/userManagement/9.0/metadata.xml
Labels: qa: Can't merge

#1635 Fixes #18260: Selecting "latest" version for package installation in techniques Packages only checks for existence
  techniques/applications/packageManagement/1.2/packageManagement.st
Labels: qa: Can't merge

#1637 Fixes #18408: Factory reset does not work - techniques
  techniques/system/common/1.0/update.st
Labels: qa: Can't merge

#1638 Fixes #18410: Parent will fait to trust server in some cases
  techniques/system/common/1.0/update.st
Labels: Trigger test, qa: Can't merge

#1636 Fixes #18399: Improve messages in agent about server key reset
  techniques/system/common/1.0/update.st
Labels: Ready for merge, Trigger test, qa: Can't merge

#1639 Fixes #18422:
  techniques/system/common/1.0/update.st
Labels: Ready for merge

#1640 Fixes #18434: Implement ips package repositories technique
  LICENSES/gpl-3.0-or-later.txt
  techniques/applications/ipsPackageRepositories/1.0/changelog
  techniques/applications/ipsPackageRepositories/1.0/ipsPackageRepositories.st
  techniques/applications/ipsPackageRepositories/1.0/metadata.xml
Labels: Ready for merge, qa: Can't merge
