Repository Normation/rudder-techniques, pull requests merged in 2020-09, with the labels that each got.

#1618 Fixes #18163: rudder-techniques makefile does not build, and prevent building sources
  Makefile
Labels: Ready for merge

#1619 Fixes #18176: Technique shared folder on WIndows use invalid md5 hash instead of sha256
  techniques/fileDistribution/copyGitFile/2.3/copyFileFromSharedFolder.ps1.st
Labels: Ready for merge

#1622 Fixes #18222: In HTTPS+Syslog, syslog config is not removed if agent supports https
  techniques/system/common/1.0/promises.st
Labels: Ready for merge, qa: Can't merge

#1620 Fixes #16837: userManagement produce missing reports when used in Check only mode
  techniques/systemSettings/userManagement/userManagement/9.0/userManagement.st
Labels: qa: Can't merge

#1624 Fixes #18231: Cron for Rudder agent on solaris is invalid
  techniques/system/common/1.0/cron-setup.cf
Labels: qa: Can't merge

#1623 Fixes #18228: Create an "old-school" crontab technique to manage crontab in /var/spool/cron/crontabs
  maintained-techniques
  techniques/system/common/1.0/hooks.cf
  techniques/systemSettings/systemManagement/userCronManagement/1.0/metadata.xml
  techniques/systemSettings/systemManagement/userCronManagement/1.0/userCronConfiguration.st
Labels: qa: Can't merge
