Repository Normation/rudder-techniques, pull requests merged in 2021-12, with the labels that each got.

#1737 Fixes #20381: unexpected report after upgrading Rudder from 6.2 to 7.0
  techniques/system/rudder-service-apache/1.0/apache/system_rudder_apache_webdav_configuration.cf
Labels: Trigger test

#1736 Fixes #20382: rudder is restarted in first agent run after upgrade from 6.2 to 7.0
  techniques/system/rudder-service-slapd/1.0/main.st
Labels: Trigger test

#1738 Fixes #19659: .pgpass file cannot use remote postgresql
  techniques/system/rudder-service-postgresql/1.0/main.st
  techniques/system/rudder-service-postgresql/1.0/password-check.st
Labels: Trigger test

#1740 Fixes #20427: missing default value in initial promises
  Makefile
  properties.json
Labels: qa: Can't merge, Trigger test

#1739 Fixes #20386: Dockerize technique tests
  Jenkinsfile
  Makefile
  ci/cf-promises.Dockerfile
  ci/pylint.Dockerfile
  ci/rust.sh
  ci/shellcheck.Dockerfile
  ci/typos.Dockerfile
  ci/user.sh
  qa-test
  scripts/check-techniques.sh
Labels: qa: Can't merge, Ready for merge, Trigger test

#1741 Fixes #20442: Dockerize technique tests - missing python dependency
  ci/cf-promises.Dockerfile
Labels: Ready for merge, Trigger test

#1742 Fixes #20476: Don't insert partial runs as run logs - inventory detection doesn't work
  techniques/system/common/1.0/promises.st
Labels: Trigger test
