Repository Normation/rudder-techniques, pull requests merged in 2021-06, with the labels that each got.

#1670 Fixes #19355: Add ci check for techniques
  Jenkinsfile
  qa-test
  scripts/check-techniques.sh
  techniques/fileConfiguration/fileManagement/4.1/manageFilesAndFolders.st
  techniques/fileDistribution/checkGenericFileContent/8.0/checkGenericFileContent.st
  techniques/fileDistribution/fileTemplate/1.0/fileTemplate.ps1.st
  techniques/jobScheduling/jobScheduler/2.0/job_scheduler.st
  techniques/jobScheduling/jobScheduler/3.0/job_scheduler.st
  techniques/system/common/1.0/hooks.cf
  techniques/system/common/1.0/promises.st
  techniques/system/common/1.0/properties.cf
  techniques/system/common/1.0/update.st
  techniques/system/inventory/1.0/fusionAgent.st
  techniques/system/server-roles/1.0/servers-by-role.cf
  techniques/systemSettings/misc/clockConfiguration/3.2/clockConfiguration.st
  techniques/systemSettings/networking/hostsConfiguration/2.0/hostsConfiguration.st
  techniques/systemSettings/networking/nfsClient/3.0/metadata.xml
  techniques/systemSettings/process/servicesManagement/3.0/servicesManagement.st
  techniques/systemSettings/remoteAccess/sshConfiguration/5.0/bodies.st
  techniques/systemSettings/remoteAccess/sshConfiguration/5.0/config.st
  techniques/systemSettings/systemManagement/cronManagement/3.1/metadata.xml
  techniques/systemSettings/systemManagement/cronManagement/3.2/metadata.xml
  techniques/systemSettings/systemManagement/fstabConfiguration/4.0/metadata.xml
  techniques/systemSettings/systemManagement/motdConfiguration/3.3/motd.ps1.st
Labels: Trigger test, qa: Can't merge

#1671 Fixes #19356: Add ci check for techniques - 6.2 fixes
  techniques/systemSettings/systemManagement/userCronManagement/1.0/metadata.xml
Labels: Trigger test

#1672 Fixes #19358: Add ci checks for techniques - 7.0 fixes
  techniques/system/inventory/1.0/fusionAgent.st
Labels: Trigger test

#1674 Fixes #19431: Invalid reporting in file content technique
  techniques/fileDistribution/checkGenericFileContent/8.0/checkGenericFileContent.st
Labels: Trigger test

#1675 Fixes #19433: Typo in inventory technique file
  techniques/system/inventory/1.0/fusionAgent.st
Labels: Trigger test

#1654 Fixes #19089: Add a rudder webapp system technique
  maintained-techniques
  techniques/system/rudderWebapp/1.0/alive-check.cf
  techniques/system/rudderWebapp/1.0/compress-webapp-log.cf
  techniques/system/rudderWebapp/1.0/integrity-check.cf
  techniques/system/rudderWebapp/1.0/main.st
  techniques/system/rudderWebapp/1.0/metadata.xml
  techniques/system/rudderWebapp/1.0/metrics-reporting.cf
  techniques/system/rudderWebapp/1.0/password-check.cf
Labels: Trigger test, qa: Can't merge

#1656 Fixes #19103: Add a Rudder postgres system technique
  maintained-techniques
  techniques/system/rudderPostgresql/1.0/main.st
  techniques/system/rudderPostgresql/1.0/metadata.xml
  techniques/system/rudderPostgresql/1.0/password-check.st
Labels: Trigger test

#1655 Fixes #19038: Add a relay technique
  maintained-techniques
  techniques/system/rudderApache/1.0/apache/main.cf
  techniques/system/rudderApache/1.0/apache/system_rudder_apache_networks_configuration.cf
  techniques/system/rudderApache/1.0/apache/system_rudder_apache_webdav_configuration.cf
  techniques/system/rudderApache/1.0/common/reload_rudder_services.cf
  techniques/system/rudderApache/1.0/metadata.xml
  techniques/system/rudderRelay/1.0/metadata.xml
  techniques/system/rudderRelay/1.0/relayd/relayd.cf
  techniques/system/rudderRelay/1.0/relayd/relayd.conf.tpl
Labels: Trigger test, qa: Can't merge

#1677 Fixes #19452: Fix several typos with the new technique version
  techniques/system/rudderPostgresql/1.0/main.st
  techniques/system/rudderPostgresql/1.0/password-check.st
Labels: Trigger test

#1676 Fixes #19445: File content always reports repair when "Replace content" is selected
  techniques/fileDistribution/checkGenericFileContent/8.0/checkGenericFileContent.st
Labels: Trigger test

#1673 Fixes #19403: User technique should show unix option by default
  techniques/systemSettings/userManagement/userManagement/9.0/metadata.xml
Labels: Trigger test

#1657 Fixes #19105: Add a Rudder slapd system technique
  maintained-techniques
  techniques/system/rudderSlapd/1.0/main.st
  techniques/system/rudderSlapd/1.0/metadata.xml
Labels: Ready for merge

#1678 Fixes #19477: Policy validation at the end of policy generation spends too much time evaluating things
  techniques/applications/repoGpgKeyManagement/1.1/repoGpgKeyManagement.st
  techniques/system/common/1.0/environment-variables.cf
  techniques/system/common/1.0/hooks.cf
  techniques/system/server-roles/1.0/component-check.cf
  techniques/system/server-roles/1.0/password-check.cf
  techniques/systemSettings/misc/genericCommandVariableDefinition/3.0/genericCommandVariableDefinition.st
  techniques/systemSettings/misc/variableFromJsonFile/2.0/variableFromJsonFile.st
  techniques/systemSettings/remoteAccess/sshKeyDistribution/3.0/sshKeyDistribution.st
Labels: Trigger test, qa: Can't merge

#1679 Fixes #19496: Use agent certificate in place of rudder.crt
  techniques/system/distributePolicy/1.0/apache-acl.cf
Labels: Trigger test
